### ISSUE TITLE
Enable context_dependent option for Rubocop Style/BracesAroundHashParameters

### ISSUE THREAD

**Issue by mitchlloyd** [aptible/aptible-tasks#23]
Per https://github.com/bbatsov/rubocop/issues/2063, there is an unfortunate effect of _always_ removing optional braces around hash parameters. Something like this is a violation:

```ruby
add_users({ name: 'Mitch' }, { name: 'Gib' })
```

And the fix is:

```ruby
add_users({ name: 'Mitch' }, name: 'Gib')
```

I'm running into this issue when using the RSpec `include` matcher.

The alleged fix is:

```
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
```

**Comment by krallin** [comment]
:+1: :+1: :+1: :+1: :+1:

**Comment by krallin** [comment]
(assuming the fix does fix it)

**Comment by mitchlloyd** [comment]
Ok! Will give it a try and see how it works.

**Comment by mitchlloyd** [comment]
Tested locally in gridiron. This no longer reports violations on code like this:

```ruby
add_users({ name: 'Mitch' }, { name: 'Gib' })
```

but still reports violations on code like this:

```ruby
my_method('string', { optional: 'hi' })
```
